### ISSUE TITLE
Create a forum solution

### ISSUE THREAD

**Issue by alexarje** [NIME-conference/nime-website#16]
There seems to be a community interest in setting up a forum of some kind on nime.org.

**Comment by cpmpercussion** [comment]
@disastrid suggested flarum from great Bela experience, I have a test site set up at [forum.nime.org](https://forum.nime.org)

I'm just thinking about the best way to host this, probably a shared-hosting account for our community with credentials we can pass around (right now it's on my personal Namecheap account)

If all approve, I can move forward with a different host and we can announce it!

Only feature I am looking for right now is email notification on **any** post (i.e., if someone wanted to use it like a mailing list).

**Comment by cpmpercussion** [comment]
Ok, https://forum.nime.org/ is now hosted on a NIME Dreamhost account (I'll send credentials over email). And should be ready to rock, if you folks (@alexarje @disastrid ) make accounts, I'll make you admins 😄 

PS @disastrid it was a bit tricky to get running on Dreamhost!

**Comment by alexarje** [comment]
Great! Thanks for getting this up and running!

**Comment by cpmpercussion** [comment]
welllll. I got a bit worried that the flarum wasn't working well enough. I've actually set up a discourse on the lowest end digital ocean VPS: discourse.nime.org

Discourse is much heavier than flarum (has messaging and lots more features), and I'm just a bit concerned that we need that kind of stuff to support the community features we want.

What do you folks think?

**Comment by alexarje** [comment]
The mailing list currently has around 1500 subscribers, so we are talking about a quite large group of people that could potentially want to use the forum. So, yes, I imagine that more advanced and flexible solutions could be a good idea. What are the cost differences here (both in terms of maintenance and server costs)?

**Comment by cpmpercussion** [comment]
The cost for running Flarum on Dreamhost is currently 5USD per month (goes up to 10USD after the first year), and the performance never improves. I think it's actually not a great solution because if you need better performance you have to go for a VPS anyway, and it's almost impossible to upgrade flarum or add extensions in their service.

The cost for the VPS on DigitalOcean is 5USD (1GB Ram, 1vCPU) + 1USD per month for backups, and if we need more performance, we can easily scale to 10-15USD per month (to get 2GB ram and 2vCPUs).

I'm more convinced now that discourse is the higher end solution and the better features are worth it for supporting our  community. The shared hosting route is not actually cheaper and more hassle.

I guess it's potentially more hassle to maintain a VPS ourselves, but the better performance and features will make it worthwhile. In practice I haven't had issues with a few VPSs that I already run for other tasks.

**Comment by cpmpercussion** [comment]
wow you can setup discourse to accept posts through email as well - https://meta.discourse.org/t/start-a-new-topic-via-email/62977 , we could actually (eventually) just completely replace the google group with our own discourse.

This would be possible for users who can't access google groups for geographic or political reasons.

**Comment by alexarje** [comment]
That is interesting, although I guess we should try it out a little before we decide to skip the mailing list. I guess they serve to different needs (and possibly user groups).

**Comment by cpmpercussion** [comment]
Ok I think I've seen enough, I've connected the discourse forum to the https://forum.nime.org 

I think it will be great for our community, now to start some conversations there, I'd like to send out invites to a few community members to join and make a post or two to start things out. For now, I've set @alexarje and @disastrid as admins and mods, I don't think we need to immediately go and make a bunch of mods, but just having a few members with pertinent NIME conversations would be good.

A few notes on maintenance, I would like to install SSH keys for a you admins in the server, so you could get into it in an emergency. I've set the droplet to take a snapshot every week, and discourse can back itself up to AWS (but I haven't gotten that set up yet).

**Comment by cpmpercussion** [comment]
I suppose we could continue some of this discussion on https://forum.nime.org/c/site-feedback/ ?

**Comment by alexarje** [comment]
Yes, good idea! I will add some more content in the coming days, and when we see how things pan out, we can send out info to the whole community.

**Comment by disastrid** [comment]
Thanks so much for taking the initiative on this @cpmpercussion! I've been checking out the forum and it looks great.

Just a heads up that I tried to get to the admin interface via the link in the notification and it 404s because it redirects to discourse.nime.org. Is there any known way to update all these links? If not I can look into it.

Some to-dos that we might consider:
- A Code of Conduct doc that is forum-specific. The current link goes to one for the in-person conference, but I think this needs to be more focused for online communication. I can draft this if it's useful.
- Creating reate some categories for posts - like Jobs, Studies (as these are often posted to the list), Students, Conference ... there's probably lots more, but I think these can only be created by Admins.

**Comment by cpmpercussion** [comment]
oh the notification link is probably out of date since I switched the install over to forum.nime.org.

Maybe it's just that bit of text in the notification message? The admin link in the hamburger menu seems to be correctly  going to [https://forum.nime.org/admin](https://forum.nime.org/admin)

There's a **lot** in the admin menu, still learning my way around discourse at this point, but it looks really great.

Having a forum specific code of conduct is a great idea. I think it makes a real difference for inclusion to set out the behaviour we expect. If you wrote up some text for this, that would be great!

Adding categories also good, I don't think it's urgent to add **too** many, as we can recategorise things as we find out how folks end up using the forum.

You're an admin, so you should be able to add or edit categories from: https://forum.nime.org/categories

There's also subcategories and tags (currently disabled) which we could use to shape the structure.

**Comment by cpmpercussion** [comment]
I thought I had the web redirect working on that old discourse.nime.org address, apparently not, I've tried again but still doesn't seem to work.

THere's a slightly hairy looking way to do a big find and replace in the database (not too big right now), but hopefully it was just those few notifications from Monday which have the wrong url?

**Comment by disastrid** [comment]
Works now, thanks! 🥇

**Comment by disastrid** [comment]
@cpmpercussion As an aside, can we set up a forward-only address for forum admins? It's imperative to have a method of contact to address any issues with trolling/harassment/etc.

**Comment by cpmpercussion** [comment]
I'm going to close this for now as https://forum.nime.org is fully operational! 💯 

Any further forum discussion can happen.... on the forum!
