### ISSUE TITLE
Revise Code of Conduct

### ISSUE THREAD

**Issue by alexarje** [NIME-conference/nime-website#19]
The current [NIME Code of Conduct](https://www.nime.org/code-of-conduct/) is written specifically for the conference, but since it is now also linked from the [forum page](https://forum.nime.org/), it would be good to revise it so that it also works well there.

**Comment by disastrid** [comment]
Here's a draft. Suggestions welcome.

---

# Short version

NIME is a community for music makers, technologists, artists, musicians, scientists, and instrument builders. We are a community that acknowledges that inequality exists in this community, and aims to continuously improve how it embodies existing values of diversity and inclusion.

Communication in this forum should be respectful. If you make a mistake, apologise.

If you see someone behaving disrespectfully, please tell them to stop.

If you can't resolve an issue, contact the forum admins at forum@nime.org.

# Long Version

## About NIME

NIME is a worldwide community of instrument builders, musicians, scientists, academics, and artists. NIME strives to be inclusive of individuals of all genders, sexual orientations, ages, abilities, nationalities, ethnicities, religions, career paths, languages, body sizes, knowledge types, musical taste and technical ability.

The NIME forum was launched after the successful NIME 2020, which took place entirely online due to coronavirus restrictions. There was a strong desire within the community to continue the stimulating and exciting conversations we were having.

## Be respectful

Respectful behaviour includes:

- Being considerate, kind, helpful, and encouraging. 
- Actively avoiding language that is demeaning, discriminatory, harassing, hateful, threatening, or aggressive.

If you're unsure, ask someone.

## Look out for yourself

If you experience disrespectful behaviour and feel that you are unable to respond or don't feel that you can resolve it yourself (for any reason), please bring it to the attention of the forum admins through forum@nime.org. We will listen to you and help you to resolve the issue, or address the problem ourselves if that's more appropriate. Any messages sent to this address are confidential.

## Look out for others

The NIME community was founded on peer discussion and feedback. We believe that discourse builds a richer, more diverse community of practitioners.

We also acknowledge that inequities exist in this community, due to exclusionary factors related to gender, race, access to education, mother tongue, socioeconomic status, access to technology, and a myriad of other causes. We believe that the NIME community should be actively working against these oppressive forces, and progressing as a community towards greater inclusivity.

This means that that if you see someone behaving disrespectfully, we encourage you to respectfully discourage that behaviour. We are all in a constant state of learning, and must help one another. If you don't feel you can do this yourself, send a message to the forum admins at forum@nime.org. Any messages sent to this address are confidential.

## Don't do these things

In addition to behaving with respect and contributing to a spirit of helpfulness and encouragement, the following behaviours are strictly not allowed:

- Impersonating someone else
- Posting someone else's work as your own
- Posting offensive language, media or images
- Posting private information in public spaces

If you see any harassing or trolling behaviour, please report it immediately by sending a link to forum@nime.org.

## Apologise for mistakes

We are all learning, and we all make mistakes. If your behaviour is highlighted for being disrespectful please apologise accordingly, and consider how you might choose different words in the future.

## Consequences

The forum admins are volunteers who seek to facilitate wider communication within the NIME community, both among established members as well as newcomers. The forum admins act in the interests of the NIME community and its future.

If the forum admins determine that a forum user is behaving disrespectfully, disobeying the rules, or exhibiting any other behaviour that does not further our community or its values, the forum admins will take any action appropriate for the situation, including disabling user accounts.

**Comment by alexarje** [comment]
This is great @disastrid! I don't have any comments, so would support posting it as is. It would perhaps be good to put a cc-license, date, and version number on it when you post it?

**Comment by disastrid** [comment]
Sounds good. We should also expect that it should evolve and change over time, so a date/version number/way of suggesting edits should also be added to the end. I'll see what @cpmpercussion says about an email address - or is that something you can take care of @alexarje?

**Comment by alexarje** [comment]
Yes, I think we should consider this a living document. @cpmpercussion will need to help with an e-mail address.

**Comment by disastrid** [comment]
I've added an Admin category to the forum - only admins can post there - to collect this kind of thing, and [posted this code of conduct there](https://forum.nime.org/t/code-of-conduct/25). 

I guess we should also have a Get Started Guide or something that explains what NIME is (conference, forum, community); I'll work on that next.

**Comment by cpmpercussion** [comment]
yeehaw, we're off!

**Comment by alexarje** [comment]
Great! We need to link to the new code of conduct from the top menu on the forum page. Is that an easy fix somewhere @cpmpercussion?
